// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5k6BYHIy6tyikhBYLHqj11HwCG-p5Rk',
    appId: '1:292832458462:web:40651646ef3ff8ca6d744f',
    messagingSenderId: '292832458462',
    projectId: 'bookingapp-35075',
    authDomain: 'bookingapp-35075.firebaseapp.com',
    storageBucket: 'bookingapp-35075.appspot.com',
    measurementId: 'G-715BFREFH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaBAxyi0igBkJnP0odw40K84VNAbma1o',
    appId: '1:292832458462:android:240bff7e6b3a9ca66d744f',
    messagingSenderId: '292832458462',
    projectId: 'bookingapp-35075',
    storageBucket: 'bookingapp-35075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwY8pcMRVRC5N_lQRkK4OjGtJdJwa8EY',
    appId: '1:292832458462:ios:8c1dbc298e73ce1f6d744f',
    messagingSenderId: '292832458462',
    projectId: 'bookingapp-35075',
    storageBucket: 'bookingapp-35075.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlwY8pcMRVRC5N_lQRkK4OjGtJdJwa8EY',
    appId: '1:292832458462:ios:db5734c66afaa36b6d744f',
    messagingSenderId: '292832458462',
    projectId: 'bookingapp-35075',
    storageBucket: 'bookingapp-35075.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
